name: Elixir CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        version-file: .tool-versions
        version-type: strict

    - name: Elixir cache
      id: elixir-cache
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
        key: mix-${{ runner.os }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          mix-${{ runner.os }}-

    - name: Install dependencies
      run: mix deps.get

    - name: Setup input cache
      id: aoc-inputs
      uses: actions/cache@v4
      with:
        path: lib/**/input.txt
        key: aoc-inputs

    - name: Fetch inputs
      run: mix input.get
      env:
        AOC_SESSION: ${{ secrets.AOC_SESSION }}

    - name: Run tests
      run: mix test